name: Run Locust performance tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:

  # -------------------------
  # 1. Запуск нагрузочных тестов
  # -------------------------
  run-tests:
    name: Run performance tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Запуск Locust и генерация отчёта
      - name: Run Locust tests
        run: |
          mkdir -p reports
          locust -f locustfile.py \
                 --headless \
                 --users 10 \
                 --spawn-rate 2 \
                 --run-time 10s \
                 --html reports/index.html

      # Сохраняем папку reports как артефакт,
      # чтобы передать её в следующую джобу
      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: locust-report
          path: reports
          retention-days: 7


  # -------------------------
  # 2. Публикация отчёта на GitHub Pages
  # -------------------------
  publish-report:
    name: Publish HTML report to GitHub Pages
    runs-on: ubuntu-latest

    needs: run-tests   # эта джоба запускается после run-tests
    if: always()       # выполняем ПУСТЬ ДАЖЕ если run-tests провалится

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Загрузка артефактов
      - name: Download report artifact
        uses: actions/download-artifact@v4
        with:
          name: locust-report
          path: reports

      # Публикация в GitHub Pages
      - name: Deploy HTML report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: reports
          keep_files: true   # сохраняем старые отчёты
